### PR TITLE
Move to named VM types

### LINKED ISSUE #75: Move to named vm_types
VM Types like `small`, `medium`, and `default` are useless.  Let's use things named after the type of instance it will back, i.e. `uaa`, `api`, `router`, etc.

### PR DESCRIPTION
**Pull request by jhunt**
Gone are the days of small / medium / large.

Fixes #75

### CODE REVIEW

**Comment by jhunt** [comment]
@dennisjbell we shouldn't even need defaults...

**Comment by dennisjbell** [comment]
Not sure what you mean by 'we shouldn't even need defaults' regarding the check script -- the check script ensures that all the vm types needed exist, and this PR changes that list of named vms -- left as-is it will fail, removed it will pass even if those vm types don't exist, only to fail once bosh gets ahold of it

**Comment by jhunt** [comment]
Meaning that we don't use the `vm_type ||  "..."` spruce magic; we just hard-code the default param in the merged files.

**Comment by jhunt** [comment]
Changes posted.  Please re-review. 😁

**Comment by jhunt** [comment]
I know it won't merge, I'll handle the merge if the approval is given.

**Comment by dennisjbell** [comment]
Yeah, that merge master into the PR broke a lot of stuff -- probably best to reset your master on origin/master, then cherry pick these changes -- I approve up to commit 
163acf4  :)

**Pull request merged**
