### PR TITLE
Adding manifest changes for cflinux3 support

### PR DESCRIPTION
**Pull request by krutten**
Changes add cflinux3 code
Stack default left for cflinuxfs2

### CODE REVIEW

**Comment by Proplex** [comment]
Looks good!

Is keeping `cflinuxfs2` the default stack a good idea for now? i.e. is there any harm in making the default stack `cflinuxfs3`?

**Comment by norman-abramovitz** [comment]
The problem is if the application fails to run on cfliunixfs3, then we are causing harm.   There could custom buildpacks that have been converted yet.

**Comment by jhunt** [comment]
Can we make it easier to switch the default to fs3?  or is it just a matter of time / attrition and a future "oh-no-please-let-me-stay-on-cflinuxfs2" flag?

**Comment by krutten** [comment]
I was thinking we would just make the default in the next minor or major release.  It's a big enough change.  This was left as the old default to reduce upgrade surprises.

It should be a one line `default_stack: "cflinuxfs3"` change in the env file if they want to switch early and we can document it in the release notes.

**Comment by jhunt** [comment]
I like it.  Let's see what @thomasmitchell thinks, since he's reviewing.

**Comment by thomasmitchell** [comment]
I feel like it should be a param, solely based on the fact that we document params outside of the release notes (MANUAL.md). In the next minor/major or whatever, you'd be taking the same steps to set the default to cflinuxfs2, so its relevant to more than just these release notes - and the correct thing to do being so simple is only known if you know the way our manifest layout is.

**Comment by daviddob** [comment]
Looks like `cflinuxfs2` is officially deprecated this month and clients are asking for a roadmap to get over to `cflinuxfs3` as they are seeing deprecation warnings on app pushes now. Supporting it as a param would be a nice feature for migration and avoid breaking existing deployments.

**Comment by daviddob** [comment]
Looks like cflinuxfs2 is officially deprecated this month so it would be nice to have a roadmap to get over to cflinuxfs3 as developers will see deprecation warnings on app pushes. Supporting it as a param would be a nice feature for migration and avoid breaking existing deployments.

**Pull request merged**
